### PR TITLE
Store AppleID credentials in the Keychain

### PR DESCRIPTION
**Pull request by rrroyal**
todo before merging: set the correct bundleID for app/keychain group

### CODE REVIEW

**Comment by rrroyal** [comment]
@lonkelle

**Comment by lonkelle** [comment]
@rrroyal You're my hero for real rn!

**Comment by rrroyal** [comment]
if we're not planning on using more of keychain-related stuff i can get rid of KeychainAccess and replace it with a simple wrapper - it's always one dependency less 😶

**Comment by lonkelle** [comment]
@rrroyal Are you referring to this: https://github.com/jawshoeadan/SideServer/blob/3751f7da1e20de967557e4436a89545fd67373ab/Shared/Components/Keychain.swift#L9

What are the pros / cons in your head for that? I don't **think** we'll be using more keychain related functionality beyond what you've implemented but I'm trying to think of what we'd lose by going the simpler route. Multiple Apple ID support I suppose, but that should almost never be needed.

**Comment by rrroyal** [comment]
if we were to move to a "simpler" solution (a one without KeychainAccess), we could implement a lot more stuff ourselves - i.e. multiple Apple ID support would be easier to add with a simple wrapper than with KeychainAccess 😄

**Comment by lonkelle** [comment]
@rrroyal Ah, gotcha. So sounds like there are def pros to this direction so I think we should go for it. Any cons to the "simpler" solution that you can think of offhand?

**Comment by rrroyal** [comment]
initially more bugs? before we test on more configurations we could meet some errors, but they should be easy to fix

**Comment by lonkelle** [comment]
Based on Royal's insight, we can (and likely should) switch to the simpler solution in a future PR. This one works for what it is tho and should still be merged.

**Pull request merged**
